name: Static analyzation of cmdline app
on:
  push:
    paths:
      - app/**.dart
jobs:
  analyze_app:
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v4

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 'stable'

      - run: dart pub get
        working-directory: app
      - run: dart analyze
        working-directory: app