name: Static analyzation of Fireworks
on:
  push:
    paths:
      - app
jobs:
  analyze_app:
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v4

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 'stable'

      - run: dart analyze app
