name: Static analyzation of build scripts
on:
  push:
    paths:
      - build/**.dart
jobs:
  analyze_build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v4

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 'stable'

      - run: dart pub get
        working-directory: build
      - run: dart analyze
        working-directory: build