name: Build Clang compiler
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - name: Repository checkout
        uses: actions/checkout@v4

      - name: Install git
        run: | 
          sudo apt-get update
          sudo apt-get install git

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1

      - name: Pub get
        run: dart pub get
        working-directory: ./build/ci

      - name: Build process
        run: dart run ./build/ci/bin/build_clang.dart

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: clang-newest
          path: ./build/ci/bin/build_clang/clang-newest

