name: Build gen_snapshot for Android

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-gen-snapshot:
    runs-on: ubuntu-latest  # Alternativ: macos-latest oder windows-latest

    env:
      ANDROID_NDK_VERSION: 26.1.10909125
      TARGET_CPU: arm64
      BUILD_MODE: debug_unopt

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl git unzip python3 python3-pip python3-venv ninja-build clang cmake pkg-config libglib2.0-dev

      - name: Set up depot_tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "$GITHUB_WORKSPACE/depot_tools" >> $GITHUB_PATH

      - name: Clone Flutter engine repo
        run: |
          mkdir engine && cd engine
          fetch --nohooks flutter
          cd src
          gclient sync

      - name: Apply GN configuration (host)
        working-directory: engine/src
        run: |
          ./flutter/tools/gn --unoptimized

      - name: Apply GN configuration (android target)
        working-directory: engine/src
        run: |
          ./flutter/tools/gn --android --android-cpu $TARGET_CPU --unoptimized

      - name: Build host gen_snapshot
        working-directory: engine/src
        run: |
          ninja -C out/host_${BUILD_MODE} gen_snapshot

      - name: Build android runtime (dartaotruntime)
        working-directory: engine/src
        run: |
          ninja -C out/android_${BUILD_MODE}_${TARGET_CPU} dartaotruntime

      - name: Upload gen_snapshot artifact
        uses: actions/upload-artifact@v4
        with:
          name: gen_snapshot-linux64-for-android-${{ env.TARGET_CPU }}
          path: engine/src/out/host_${{ env.BUILD_MODE }}/gen_snapshot

      - name: Upload dartaotruntime artifact
        uses: actions/upload-artifact@v4
        with:
          name: dartaotruntime-android-${{ env.TARGET_CPU }}
          path: engine/src/out/android_${{ env.BUILD_MODE }}_${{ env.TARGET_CPU }}/dartaotruntime
